# Generated by Django 3.2.9 on 2021-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagline_images',
            field=models.ImageField(blank=True, null=True, upload_to='blog/post_images/tagline_images'),
        ),
    ]
