# Generated by Django 3.2.9 on 2021-12-06 08:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField()),
                ('star_icon', models.ImageField(upload_to='rooms/rating_stars')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='rooms_pics')),
                ('room_type', models.CharField(choices=[('Pernight', 'Pernight'), ('For Week', 'For Week'), ('For three days', 'For three days'), ('How you want', 'How you want')], max_length=200)),
                ('bed_type', models.CharField(choices=[('King Beds', 'King Beds'), ('Special for you', 'Special for you'), ('Italian furniture', 'Italian furniture'), ('How you want', 'How you want')], max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('size_in_ft', models.PositiveIntegerField(default=15)),
                ('capacity_persons', models.PositiveIntegerField(default=2)),
                ('rating_stars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='res_system.rating_star')),
                ('services', models.ManyToManyField(related_name='room', to='res_system.Services')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('rating_stars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='res_system.rating_star')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='res_system.room')),
            ],
        ),
    ]
