# Generated by Django 3.2.9 on 2021-12-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rating_stars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res_system.rating_star'),
        ),
    ]
