# Generated by Django 3.2.9 on 2021-12-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='size_in_ft',
            new_name='size',
        ),
    ]
