# Generated by Django 3.2.9 on 2021-12-12 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('res_system', '0003_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
