# Generated by Django 3.2.9 on 2021-12-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_system', '0005_auto_20211212_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmessage',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
